### ISSUE TITLE
Send long

### ISSUE THREAD

**Issue by miathedev** [caprica/lircj#1]
Actually, is there any way to send a long (32bit) variable using NEC (and receive it)?

With kind regards,
Mia

**Comment by caprica** [comment]
NEC?

In any case, this library simply provides a way to consume inputs from LIRC via a text-based protocol, it will tell your application whatever messages it receives from LIRC.

**Comment by miathedev** [comment]
Actually after some research i found out that my goal is not possible with lirc...
I wanted to actually transmit dynamic text over infrared to a Arduino and back in my application. And i hoped i could do it using lirc (one way transmission)

You dont know any way i could do that?

**Comment by caprica** [comment]
I have no idea, you'll have more luck posting at an Arduino forum.

**Comment by miathedev** [comment]
Actually i wont have any luck at the Arduino forum. Because my application is not Arduino related at all. This topic is too demanding for those people (in the experience i got posting questions there).

I cant imagine that theres no one that wants to send raw binary data over infrared using the pi.

But thank you very much for your answer.
